materials:
  - name: "10А500С L=2380 армозаготовка"
    aliases:
      - "10А500С L=2380 армозаготовка"
  - name: "10А500С L=930 армозаготовка"
    aliases:
      - "10А500С L=930 армозаготовка"
  - name: "12А500С L=1000 армозаготовка"
    aliases:
      - "12А500С L=1000 армозаготовка"
  - name: "12А500С L=1500 армозаготовка"
    aliases:
      - "12А500С L=1500 армозаготовка"
  - name: "6А 500C L=1060 армозаготовка"
    aliases:
      - "6А 500C L=1060 армозаготовка"
  - name: "6А500С L=1060 армозаготовка"
    aliases:
      - "6А500С L=1060 армозаготовка"
  - name: "6А500С L=1560 армозаготовка"
    aliases:
      - "6А500С L=1560 армозаготовка"
      - "6А500С L=1560 армозаготовка, шт"
  - name: "6А500С L=2090 армозаготовка"
    aliases:
      - "6А500С L=2090 армозаготовка"
      - "6А500С L=2090 армозаготовка, шт"
  - name: "6А500С L=2390 армозаготовка"
    aliases:
      - "6А500С L=2390 армозаготовка"
  - name: "6А500С L=3440 армозаготовка"
    aliases:
      - "6А500С L=3440 армозаготовка"
  - name: "6А500С L=3815 армозаготовка"
    aliases:
      - "6А500С L=3815 армозаготовка"
  - name: "6А500С L=4175 армозаготовка"
    aliases:
      - "6А500С L=4175 армозаготовка"
  - name: "6А500С L=4990 армозаготовка"
    aliases:
      - "6А500С L=4990 армозаготовка"
      - "6А500С L=4990 армозаготовка, шт"
  - name: "6А500С L=500 армозаготовка"
    aliases:
      - "6А500С L=500 армозаготовка"
  - name: "6А500С L=6940 армозаготовка"
    aliases:
      - "6А500С L=6940 армозаготовка"
  - name: "6А500С L=800 армозаготовка"
    aliases:
      - "6А500С L=800 армозаготовка"
  - name: "8А500С L=1560 армозаготовка"
    aliases:
      - "8А500С L=1560 армозаготовка"
  - name: "8А500С L=2000 армозаготовка"
    aliases:
      - "8А500С L=2000 армозаготовка"
      - "8А500С L=2000 армозаготовка, шт"
  - name: "8А500С L=2090 армозаготовка"
    aliases:
      - "8А500С L=2090 армозаготовка"
      - "8А500С L=2090 армозаготовка, шт"
  - name: "8А500С L=3440 армозаготовка"
    aliases:
      - "8А500С L=3440 армозаготовка"
      - "8А500С L=3440 армозаготовка, шт"
  - name: "8А500С L=450 армозаготовка"
    aliases:
      - "8А500С L=450 армозаготовка"
  - name: "8А500С L=690 армозаготовка"
    aliases:
      - "8А500С L=690 армозаготовка"
  - name: "8А500С L=6940 армозаготовка"
    aliases:
      - "8А500С L=6940 армозаготовка"
      - "8А500С L=6940 армозаготовка, шт"
  - name: "8А500С L=800 армозаготовка"
    aliases:
      - "8А500С L=800 армозаготовка"
  - name: "Bergauf Грунтовка для стен глубокого проникновения бергауф TIEFGRUNT 10л 24514"
    aliases:
      - "Bergauf Грунтовка для стен глубокого проникновения бергауф TIEFGRUNT 10л 24514"
  - name: "Connector Восковая антиадгизная разделительная смазка ВСМ VSM"
    aliases:
      - "Connector Восковая антиадгизная разделительная смазка ВСМ VSM"
  - name: "ERA Решетка вентиляционная вытяжка АБС 150х150, бел. 1515Р 233-014"
    aliases:
      - "ERA Решетка вентиляционная вытяжка АБС 150х150, бел. 1515Р 233-014"
  - name: "А3 Краска фасадная"
    aliases:
      - "А3 Краска фасадная"
  - name: "Арматура 6мм А500С ГОСТ 34028-16 (кг)"
    aliases:
      - "Арматура 6мм А500С ГОСТ 34028-16 (кг)"
  - name: "Арматура 8мм А500С ГОСТ 34028-16"
    aliases:
      - "Арматура 8мм А500С ГОСТ 34028-16"
  - name: "Арматура 8мм А500С ГОСТ 34028-16 (т)"
    aliases:
      - "Арматура 8мм А500С ГОСТ 34028-16 (т)"
  - name: "Арматура A500C ф8 мм (кг)"
    aliases:
      - "Арматура A500C ф8 мм (кг)"
  - name: "Арматура А240 ф12 мм"
    aliases:
      - "Арматура А240 ф12 мм"
  - name: "Арматура А240 ф16 мм, упак 4т"
    aliases:
      - "Арматура А240 ф16 мм, упак 4т"
  - name: "Арматура А500С ф8 мм"
    aliases:
      - "Арматура А500С ф8 мм"
  - name: "Арматура А500С ф8 мм (т)"
    aliases:
      - "Арматура А500С ф8 мм (т)"
  - name: "Арматурная сетка 100*100 2,0*6,0 ф8 ТУ 25.93.13-001-46438954-2021"
    aliases:
      - "Арматурная сетка 100*100 2,0*6,0 ф8 ТУ 25.93.13-001-46438954-2021"
  - name: "Арматурная сетка 200*200 2,0*6,0 ф6 ТУ 25.93.13-001-46438954-2021"
    aliases:
      - "Арматурная сетка 200*200 2,0*6,0 ф6 ТУ 25.93.13-001-46438954-2021"
  - name: "Брус профилированный 150*150*6000 1 сорт"
    aliases:
      - "Брус профилированный 150*150*6000 1 сорт"
  - name: "БСТ В15 F 50 W2 КРК"
    aliases:
      - "БСТ В15 F 50 W2 КРК"
  - name: "БСТ В25"
    aliases:
      - "БСТ В25"
  - name: "БСТ В25 (с 0,65 по 0,85)"
    aliases:
      - "БСТ В25 (с 0,65 по 0,85)"
  - name: "БСТ В40 F150 W8 (ЖБИ)"
    aliases:
      - "БСТ В40 F150 W8 (ЖБИ)"
  - name: "БСТ В40 F150 W8 (ЖБИ) (от 9 до 11)"
    aliases:
      - "БСТ В40 F150 W8 (ЖБИ) (от 9 до 11)"
  - name: "БСТ В40 F150 W8 (ЖБИ) (придел от 9.00 до 11.00)"
    aliases:
      - "БСТ В40 F150 W8 (ЖБИ) (придел от 9.00 до 11.00)"
  - name: "БСТ В40 F150 W8 (ЖБИ)*"
    aliases:
      - "БСТ В40 F150 W8 (ЖБИ)*"
  - name: "БСТ В40 F150 W8 (КРК)"
    aliases:
      - "БСТ В40 F150 W8 (КРК)"
  - name: "БСТ В40 F150 W8 (КРК) (от 9 до 11)"
    aliases:
      - "БСТ В40 F150 W8 (КРК) (от 9 до 11)"
  - name: "БСТ В40 F150 W8 (КРК) (придел от 8,5 до 10,5)"
    aliases:
      - "БСТ В40 F150 W8 (КРК) (придел от 8,5 до 10,5)"
  - name: "БСТ В40 F150 W8 (КРК) (с 10,65 по 12,65)"
    aliases:
      - "БСТ В40 F150 W8 (КРК) (с 10,65 по 12,65)"
  - name: "БСТ В40 F150 W8 (КРК)(9-11)"
    aliases:
      - "БСТ В40 F150 W8 (КРК)(9-11)"
  - name: "БСТ В40 F150 W8 (КРК)*"
    aliases:
      - "БСТ В40 F150 W8 (КРК)*"
  - name: "Бытовой провод ПРОВОДНИК пвс 4x4 мм2, 15м, OZ48613L15"
    aliases:
      - "Бытовой провод ПРОВОДНИК пвс 4x4 мм2, 15м, OZ48613L15"
  - name: "Бытовой провод ПРОВОДНИК пвс 5x10 мм2, 20м, OZ61828L20"
    aliases:
      - "Бытовой провод ПРОВОДНИК пвс 5x10 мм2, 20м, OZ61828L20"
  - name: "Выключатель автоматический ЗП 40А характеристика С 4,5кА IEK ВА47-29 MVA20-3-040-С"
    aliases:
      - "Выключатель автоматический ЗП 40А характеристика С 4,5кА IEK ВА47-29 MVA20-3-040-С"
  - name: "Г-350-350-6 армозаготовка"
    aliases:
      - "Г-350-350-6 армозаготовка"
  - name: "Г-350-350-8 армозаготовка"
    aliases:
      - "Г-350-350-8 армозаготовка"
  - name: "Г-500-500-8 армозаготовка"
    aliases:
      - "Г-500-500-8 армозаготовка"
  - name: "Г-500-500-8* армозаготовка"
    aliases:
      - "Г-500-500-8* армозаготовка"
  - name: "Г-550-550-10 армозаготовка"
    aliases:
      - "Г-550-550-10 армозаготовка"
  - name: "Гибкий кабель ПРОВОДНИК кгтп-хл 5x25 мм2, 5м, OZ321314L5"
    aliases:
      - "Гибкий кабель ПРОВОДНИК кгтп-хл 5x25 мм2, 5м, OZ321314L5"
  - name: "Гофротруба ПНД д32 с протяжкой черная"
    aliases:
      - "Гофротруба ПНД д32 с протяжкой черная"
  - name: "Грунтовка глуб.проникновения для наруж и внутр. работ 10 л канистра"
    aliases:
      - "Грунтовка глуб.проникновения для наруж и внутр. работ 10 л канистра"
  - name: "ЗД-1 закладная деталь"
    aliases:
      - "ЗД-1 закладная деталь"
  - name: "ЗД-2 закладная деталь"
    aliases:
      - "ЗД-2 закладная деталь"
  - name: "К-2090-170-8 армокаркас"
    aliases:
      - "К-2090-170-8 армокаркас"
  - name: "К-2930-70-8 армокаркас"
    aliases:
      - "К-2930-70-8 армокаркас"
  - name: "К-310-170-8 армокаркас"
    aliases:
      - "К-310-170-8 армокаркас"
  - name: "К-3440-100-8 армокаркас"
    aliases:
      - "К-3440-100-8 армокаркас"
  - name: "К-3440-170-8 армокаркас"
    aliases:
      - "К-3440-170-8 армокаркас"
      - "К-3440-170-8 армокаркас, шт"
  - name: "К-4840-170-8 армокаркас"
    aliases:
      - "К-4840-170-8 армокаркас"
  - name: "К-560-170-8 армокаркас"
    aliases:
      - "К-560-170-8 армокаркас"
  - name: "К-690-170-8 армокаркас"
    aliases:
      - "К-690-170-8 армокаркас"
      - "К-690-170-8 армокаркас, шт"
  - name: "К-6940-100-8 армокаркас"
    aliases:
      - "К-6940-100-8 армокаркас"
  - name: "К-6940-170-8 армокаркас"
    aliases:
      - "К-6940-170-8 армокаркас"
      - "К-6940-170-8 армокаркас, шт"
  - name: "К-760-170-8 армокаркас"
    aliases:
      - "К-760-170-8 армокаркас"
  - name: "К-760-170-8* армокаркас"
    aliases:
      - "К-760-170-8* армокаркас"
  - name: "К-800-170-8 армокаркас"
    aliases:
      - "К-800-170-8 армокаркас"
      - "К-800-170-8 армокаркас, шт"
  - name: "КА-2540-100-86-8 армокаркас"
    aliases:
      - "КА-2540-100-86-8 армокаркас"
      - "КА-2540-100-86-8 армокаркас, шт"
  - name: "КА-2930-60-52-8 армокаркас"
    aliases:
      - "КА-2930-60-52-8 армокаркас"
  - name: "КА-3440-100-86-8 армокаркас"
    aliases:
      - "КА-3440-100-86-8 армокаркас"
  - name: "КА-3440-100-86-8* армокаркас"
    aliases:
      - "КА-3440-100-86-8* армокаркас"
  - name: "Кабель ВВГнг (А) 3х1,5 FRLS П ГОСТ"
    aliases:
      - "Кабель ВВГнг (А) 3х1,5 FRLS П ГОСТ"
  - name: "Кабель ВВГ-Пнг (А) 3х1,5 LS"
    aliases:
      - "Кабель ВВГ-Пнг (А) 3х1,5 LS"
  - name: "КГ-2930-250-8А армокаркас"
    aliases:
      - "КГ-2930-250-8А армокаркас"
  - name: "КГ-2930-250-8В армокаркас"
    aliases:
      - "КГ-2930-250-8В армокаркас"
  - name: "Кладочная сетка 200*200 2,0*3,0 ф5 ГОСТ 23279-2012"
    aliases:
      - "Кладочная сетка 200*200 2,0*3,0 ф5 ГОСТ 23279-2012"
  - name: "Кладочная сетка 200*200 2,0*6,0 ф5"
    aliases:
      - "Кладочная сетка 200*200 2,0*6,0 ф5"
  - name: "Кладочная сетка 200*200 2,0*6,0 ф5,"
    aliases:
      - "Кладочная сетка 200*200 2,0*6,0 ф5,"
  - name: "Коробка У-192 (96*30 мм) полипропилен"
    aliases:
      - "Коробка У-192 (96*30 мм) полипропилен"
  - name: "Коробка У-195 (70*30 мм) полипропилен"
    aliases:
      - "Коробка У-195 (70*30 мм) полипропилен"
  - name: "КП-1 армокаркас"
    aliases:
      - "КП-1 армокаркас"
  - name: "КП-2 армакаркас"
    aliases:
      - "КП-2 армакаркас"
  - name: "КП-2 армокаркас"
    aliases:
      - "КП-2 армокаркас"
  - name: "КР-1830-300-10 армокаркас"
    aliases:
      - "КР-1830-300-10 армокаркас"
  - name: "КР-2000-300-10 армокаркас"
    aliases:
      - "КР-2000-300-10 армокаркас"
  - name: "КР-2500-300-10 армокаркас"
    aliases:
      - "КР-2500-300-10 армокаркас"
  - name: "КР-2800-300-10 армокаркас"
    aliases:
      - "КР-2800-300-10 армокаркас"
      - "КР-2800-300-10 армокаркас, шт"
  - name: "КР-2960-300-10 армокаркас"
    aliases:
      - "КР-2960-300-10 армокаркас"
  - name: "КР-2960-300-10 армокаркас НЕ использовать"
    aliases:
      - "КР-2960-300-10 армокаркас НЕ использовать"
  - name: "КР-3400-300-10 армокаркас"
    aliases:
      - "КР-3400-300-10 армокаркас"
  - name: "КР-3880-300-12 армокаркас"
    aliases:
      - "КР-3880-300-12 армокаркас"
      - "КР-3880-300-12 армокаркас, шт"
  - name: "МР-3 D4 Электроды Тантал (5кг)"
    aliases:
      - "МР-3 D4 Электроды Тантал (5кг)"
  - name: "Опалубка под плиту перекрытия"
    aliases:
      - "Опалубка под плиту перекрытия"
  - name: "Опалубка под продольную стену тип А"
    aliases:
      - "Опалубка под продольную стену тип А"
  - name: "Опалубка под продольную стену тип В"
    aliases:
      - "Опалубка под продольную стену тип В"
  - name: "Опалубка под торцевую стену тип А"
    aliases:
      - "Опалубка под торцевую стену тип А"
  - name: "Опалубка под торцевую стену тип В"
    aliases:
      - "Опалубка под торцевую стену тип В"
  - name: "П1 армозаготовка"
    aliases:
      - "П1 армозаготовка"
  - name: "П-1 армозаготовка"
    aliases:
      - "П-1 армозаготовка"
  - name: "П-300-70-8 армозаготовка"
    aliases:
      - "П-300-70-8 армозаготовка"
      - "П-300-70-8 армозаготовка, шт"
  - name: "П-350-60-6 армозаготовка"
    aliases:
      - "П-350-60-6 армозаготовка"
  - name: "П-370-40-6 армозаготовка"
    aliases:
      - "П-370-40-6 армозаготовка"
      - "П-370-40-6 армозаготовка, шт"
  - name: "П-370-50-6 (6А500С L=4840) армозаготовка"
    aliases:
      - "П-370-50-6 (6А500С L=4840) армозаготовка"
  - name: "П-370-50-6 армозаготовка"
    aliases:
      - "П-370-50-6 армозаготовка"
      - "П-370-50-6 армозаготовка, шт"
  - name: "П-370-60-6 армозаготовка"
    aliases:
      - "П-370-60-6 армозаготовка"
      - "П-370-60-6 армозаготовка, шт"
  - name: "П-400-70-8 армозагатовка"
    aliases:
      - "П-400-70-8 армозагатовка"
  - name: "П-400-70-8 армозаготовка"
    aliases:
      - "П-400-70-8 армозаготовка"
      - "П-400-70-8 армозаготовка, шт"
  - name: "Перегородка для блока КИ"
    aliases:
      - "Перегородка для блока КИ"
  - name: "Провод медный ПуГВ 35(ПВ-3 35) синий 14111"
    aliases:
      - "Провод медный ПуГВ 35(ПВ-3 35) синий 14111"
  - name: "Провод медный ПуГВ 70(ПВ-3 70) белый 14113"
    aliases:
      - "Провод медный ПуГВ 70(ПВ-3 70) белый 14113"
  - name: "Провод медный ПуГВнг (А)-LS 1х16 белый 14455"
    aliases:
      - "Провод медный ПуГВнг (А)-LS 1х16 белый 14455"
  - name: "Проволка вязальная d=1,2мм (кг)"
    aliases:
      - "Проволка вязальная d=1,2мм (кг)"
  - name: "Проволока 1,2мм ТОЧ ГОСТ 3282 (5кг)"
    aliases:
      - "Проволока 1,2мм ТОЧ ГОСТ 3282 (5кг)"
  - name: "Проволока 1.2-ОЧ терм обр"
    aliases:
      - "Проволока 1.2-ОЧ терм обр"
      - "Проволока 1.2-ОЧ терм обр, кг"
  - name: "Проволока ВР-1 5мм"
    aliases:
      - "Проволока ВР-1 5мм"
  - name: "Проволока ВР-1 5мм ГОСТ 6727-80"
    aliases:
      - "Проволока ВР-1 5мм ГОСТ 6727-80"
  - name: "Проволока ВР-1 5мм ГОСТ 6727-80 (кг)"
    aliases:
      - "Проволока ВР-1 5мм ГОСТ 6727-80 (кг)"
  - name: "Проволока ВР-1 5мм ГОСТ 6727-80 (т)"
    aliases:
      - "Проволока ВР-1 5мм ГОСТ 6727-80 (т)"
  - name: "Проволока ВР-1 5мм ГОСТ6727-80 (кг)"
    aliases:
      - "Проволока ВР-1 5мм ГОСТ6727-80 (кг)"
  - name: "Проволока вязальная d=1,2мм"
    aliases:
      - "Проволока вязальная d=1,2мм"
  - name: "Проволока вязальная d=1,2мм (кг)"
    aliases:
      - "Проволока вязальная d=1,2мм (кг)"
  - name: "Проволока вязяльная d=1,2мм (кг)"
    aliases:
      - "Проволока вязяльная d=1,2мм (кг)"
  - name: "Сетка С-2600-3440-6-1"
    aliases:
      - "Сетка С-2600-3440-6-1"
      - "Сетка С-2600-3440-6-1, шт"
  - name: "Сетка С-3440-2930-5-1"
    aliases:
      - "Сетка С-3440-2930-5-1"
      - "Сетка С-3440-2930-5-1, шт"
  - name: "Сетка С-6980-2930-5-1"
    aliases:
      - "Сетка С-6980-2930-5-1"
  - name: "Сетка С-6980-2930-5-5"
    aliases:
      - "Сетка С-6980-2930-5-5"
  - name: "Сетка С-6980-3440-6-1"
    aliases:
      - "Сетка С-6980-3440-6-1"
  - name: "Сетка С-6980-3440-8-3"
    aliases:
      - "Сетка С-6980-3440-8-3"
  - name: "Смазка для опалубки ТираФорм (1 бочка=200л)"
    aliases:
      - "Смазка для опалубки ТираФорм (1 бочка=200л)"
      - "Смазка для опалубки ТираФорм (1 бочка=200л), л"
  - name: "Смазка для распалубки Forma CS-10"
    aliases:
      - "Смазка для распалубки Forma CS-10"
  - name: "Смазка для распалубки Forma CS-10 (кг)"
    aliases:
      - "Смазка для распалубки Forma CS-10 (кг)"
  - name: "Смесь МБР-400 М (25кг) зима"
    aliases:
      - "Смесь МБР-400 М (25кг) зима"
  - name: "Стретч пленка 20мкм*500мм б/цв"
    aliases:
      - "Стретч пленка 20мкм*500мм б/цв"
  - name: "Труба гофрированная REXANT 28-0400-2 из ПВХ с зонтом, 40 мм (бухта 15м/уп) (28-0400-2)"
    aliases:
      - "Труба гофрированная REXANT 28-0400-2 из ПВХ с зонтом, 40 мм (бухта 15м/уп) (28-0400-2)"
  - name: "Труба профильная 100х100х7мм L=6м"
    aliases:
      - "Труба профильная 100х100х7мм L=6м"
  - name: "Труба профильная 100х50х4 мм, L-12 м; ГОСТ 8645-82 + резка пополам"
    aliases:
      - "Труба профильная 100х50х4 мм, L-12 м; ГОСТ 8645-82 + резка пополам"
  - name: "Труба профильная 30х30х2 мм, L-6 м; ГОСТ 8639-82"
    aliases:
      - "Труба профильная 30х30х2 мм, L-6 м; ГОСТ 8639-82"
  - name: "Труба профильная 40х40х3 мм, L-6 м; ГОСТ 8639-82"
    aliases:
      - "Труба профильная 40х40х3 мм, L-6 м; ГОСТ 8639-82"
  - name: "Труба профильная 50х50х5мм L=6м т"
    aliases:
      - "Труба профильная 50х50х5мм L=6м т"
  - name: "Труба ПЭ-100 32*2,4"
    aliases:
      - "Труба ПЭ-100 32*2,4"
  - name: "Трубы проф, ГОСТ 13663-86, 8639-82, 50*50*4"
    aliases:
      - "Трубы проф, ГОСТ 13663-86, 8639-82, 50*50*4"
  - name: "Углекислота (кг)"
    aliases:
      - "Углекислота (кг)"
  - name: "Уголок 100х100х8мм ГОСТ 8509-93 (2 отрезка по 6м)(кг)"
    aliases:
      - "Уголок 100х100х8мм ГОСТ 8509-93 (2 отрезка по 6м)(кг)"
  - name: "Фанера ламинированная 21*1250*2500мм сорт 1/1 F/F LOGO/BROWN"
    aliases:
      - "Фанера ламинированная 21*1250*2500мм сорт 1/1 F/F LOGO/BROWN"
  - name: "Фанера ФСФ ламинированная Е-1 сорт I/I 21 мм 2440х1220"
    aliases:
      - "Фанера ФСФ ламинированная Е-1 сорт I/I 21 мм 2440х1220"
  - name: "Фиксатор \"Звездочка\" 15 мм"
    aliases:
      - "Фиксатор \"Звездочка\" 15 мм"
  - name: "Фиксатор \"Звездочка\" 15мм"
    aliases:
      - "Фиксатор \"Звездочка\" 15мм"
  - name: "Фиксатор 15мм"
    aliases:
      - "Фиксатор 15мм"
  - name: "Фиксатор 20 мм"
    aliases:
      - "Фиксатор 20 мм"
  - name: "Фиксатор 20мм"
    aliases:
      - "Фиксатор 20мм"
  - name: "Фиксатор арматуры 5/30"
    aliases:
      - "Фиксатор арматуры 5/30"
  - name: "Фиксатор потолочная опора 20/25/30/35, Усиленный"
    aliases:
      - "Фиксатор потолочная опора 20/25/30/35, Усиленный"
  - name: "Фиксатор Стульчик 20мм"
    aliases:
      - "Фиксатор Стульчик 20мм"
  - name: "Фиксатор Стульчик-35"
    aliases:
      - "Фиксатор Стульчик-35"
  - name: "Швеллер 14П ГОСТ 8240-97 (7 и 5м)(кг)"
    aliases:
      - "Швеллер 14П ГОСТ 8240-97 (7 и 5м)(кг)"
  - name: "Электроды GOODEL МР-3 3,0 мм (5,0 кг) зеленые розница"
    aliases:
      - "Электроды GOODEL МР-3 3,0 мм (5,0 кг) зеленые розница"
