prices:
  - name: "БП-70.35.30-1.1А"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП-70.35.30-1.1А комп. №1"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП-70.35.30-1.1А комп. №2"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП-70.35.30-1.1А комп. №3"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП-70.35.30-1.1А комп. №4"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП-70.35.30-1.1А комп. №5"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП-70.35.30-1.1А комп. №6"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП-70.35.30-1.1А комп. №7"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП-70.35.30-1.1А комп. №8"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП-70.35.30-1.1А комп. №9"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП-70.35.30-1.1А комп. №10"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП-70.35.30-1.1А комп. №11"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП-70.35.30-1.1А комп. №12 (сделана для 143 отчет)"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП70.35.30-1.1В компл. №1"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП70.35.30-1.1В компл. №2"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП70.35.30-1.1В компл. №3"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП70.30-КИ"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БлС-70.35.30-1.1А комп. №1"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БлС-70.35.30-1.1А комп. №2"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БлС-70.35.30-1.1А комп. №3"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БИ70.35.30"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БХ70.35 Мастер модель"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35 Мастер модель"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БП70.35.30-1.2В Мастер модель"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35.30-КМ"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ-70.35 КМ комп №1"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ-70.35 КМ комп №2"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ-70.35 ОКИ"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ-70.35 ОКИ компл. №1"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35.ЦС"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35.ЦС комл. №1"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35.ЦС комл. №2"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35.ЦС комл. №3"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35.ЦС комл. №4"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35.ЦС комл. №5"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35-ЛЦ комп 1"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БХ-70.35.30-1.1А"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БХ-70.35.30-1.1А комл. №1"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БХ-70.35.30-1.1А комл. №2"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БХ-70.35.30-1.1А комл. №3"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БХ-70.35.30-1.1А комл. №4"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БХ-70.35.30-1.1А комл. №5"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БХ-70.35.30-1.1А комл. №6"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БХ-70.35.30-1.1А комл. №7"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БХ-70.35.30-1.1А комл. №8"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БХ-70.35.30-1.1А комл. №9"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БХ-70.35.30-1.1А комл. №10"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "ЛМ-1 компл. №1"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "ЛМ-1 компл. №2"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "ЛП-1 компл. №1"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "Блок БТ 70.30-КИ"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35-КИ компл. №1"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35-КИ компл. №2"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35-КИ компл. №3"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35-КИ компл. №4"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35-КИ компл. №5"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35-КИ компл. №6"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "БТ70.35-КИ компл. №7"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "Перегородка для блока КИ"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "Перегородка для блока КИ комп.№1"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "Перегородка для блока КИ комп.№2"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
  - name: "Перегородка для блока КИ комп.№3"
    no_delivery_no_vat: 0
    no_delivery_vat_22: 0
    pickup_no_vat: 0
    pickup_vat_22: 0
