materials:
  - name: "Цемент ЦЕМ I 42,5Б/42,5Н"
    aliases:
      - "Цемент ЦЕМ I 42,5Б"
      - "Цемент ЦЕМ I 42,5Н"
      - "Цемент ЦЕМ I 42,5 Б"
      - "Цемент ЦЕМ I 42,5 Н"
      - "ЦЕМ I 42,5Б"
      - "ЦЕМ I 42,5Н"
  - name: "Песок средний Мк=2,0-2,5 класс 1"
    aliases:
      - "Песок средний Мк=2,0-2,5 класс 1"
      - "Песок средний Мк=2,0-2,5"
      - "Песок средний Мк 2,0-2,5"
  - name: "Гравий М1000 фракции 5-20"
    aliases:
      - "Гравий М1000 фракции 5-20"
      - "Гравий М1000 фракции 5-20 мм"
  - name: "Щебень М1200/М1400 фр.5-20 мм"
    aliases:
      - "Щебень М1200 фр.5-20 мм"
      - "Щебень М1400 фр.5-20 мм"
      - "Щебень М1200/М1400 фр.5-20 мм"
  - name: "Добавка в бетон SikaPlast PH 3554"
    aliases:
      - "Добавка в бетон SikaPlast PH 3554"
      - "SikaPlast PH3554"
      - "SikaPlast PH 3554"
  - name: "Комплексная зимняя добавка в бетон SikaTard M Nord NF"
    aliases:
      - "Комплексная зимняя добавка в бетон SikaTard M Nord NF"
      - "SikaTard M Nord NF"
      - "Sika Tard M Nord NF"
  - name: "Песок обогащенный I-II класс, модуль крупности 2,3-2,8"
    aliases:
      - "Песок обогащенный I-II класс, модуль крупности 2,3-2,8"
      - "Песок обогащенный I-II класс"
  - name: "Добавка в бетон Sika Antifreeze-300"
    aliases:
      - "Добавка в бетон Sika Antifreeze-300"
      - "Sika Antifreeze-300"
  - name: "Добавка в бетон SikaTard M-20"
    aliases:
      - "Добавка в бетон SikaTard M-20"
      - "SikaTard M-20"
  - name: "Добавка пластиф-я для бетонов и строительных раст-в FREM GIPER PREMIUM"
    aliases:
      - "Добавка пластиф-я для бетонов и строительных раст-в FREM GIPER PREMIUM"
      - "FREM GIPER PREMIUM"
  - name: "Фибра СТО 71915393-ТУ106-2011 HENDIX 1/50 коробка 25кг"
    aliases:
      - "Фибра СТО 71915393-ТУ106-2011 HENDIX 1/50 коробка 25кг"
      - "Фибра HENDIX 1/50"
