recipes:
  - name: "БСТ B7,5 F50 W2"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 180
      "Песок средний Мк=2,0-2,5 класс 1": 930
      "Гравий М1000 фракции 5-20": 1080
      "Добавка в бетон SikaPlast PH 3554": 1.26
  - name: "БСТ B7,5 F100 W4"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 250
      "Песок средний Мк=2,0-2,5 класс 1": 900
      "Гравий М1000 фракции 5-20": 1080
      "Добавка в бетон SikaPlast PH 3554": 2.13
  - name: "БСТ B10 F50 W2"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 210
      "Песок средний Мк=2,0-2,5 класс 1": 930
      "Гравий М1000 фракции 5-20": 1070
      "Добавка в бетон SikaPlast PH 3554": 1.47
  - name: "БСТ B12,5"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 220
      "Песок средний Мк=2,0-2,5 класс 1": 930
      "Гравий М1000 фракции 5-20": 1060
      "Добавка в бетон SikaPlast PH 3554": 1.65
  - name: "БСТ B12,5 F50 W2"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 220
      "Песок средний Мк=2,0-2,5 класс 1": 930
      "Гравий М1000 фракции 5-20": 1060
      "Добавка в бетон SikaPlast PH 3554": 1.65
  - name: "БСТ B15 F50 W2"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 240
      "Песок средний Мк=2,0-2,5 класс 1": 930
      "Гравий М1000 фракции 5-20": 1060
      "Добавка в бетон SikaPlast PH 3554": 1.80
  - name: "БСТ B15 F150 W6"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 310
      "Песок средний Мк=2,0-2,5 класс 1": 870
      "Гравий М1000 фракции 5-20": 1050
      "Добавка в бетон SikaPlast PH 3554": 2.64
  - name: "БСТ B20"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 270
      "Песок средний Мк=2,0-2,5 класс 1": 910
      "Гравий М1000 фракции 5-20": 1050
      "Добавка в бетон SikaPlast PH 3554": 2.16
  - name: "БСТ B20 F100 W4"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 270
      "Песок средний Мк=2,0-2,5 класс 1": 910
      "Гравий М1000 фракции 5-20": 1050
      "Добавка в бетон SikaPlast PH 3554": 2.16
  - name: "БСТ B20 F150 W6"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 310
      "Песок средний Мк=2,0-2,5 класс 1": 880
      "Гравий М1000 фракции 5-20": 1050
      "Добавка в бетон SikaPlast PH 3554": 2.64
  - name: "БСТ B22,5 F100 W4"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 280
      "Песок средний Мк=2,0-2,5 класс 1": 910
      "Гравий М1000 фракции 5-20": 1050
      "Добавка в бетон SikaPlast PH 3554": 2.24
  - name: "БСТ B25 F150 W6"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 320
      "Песок средний Мк=2,0-2,5 класс 1": 870
      "Гравий М1000 фракции 5-20": 1050
      "Добавка в бетон SikaPlast PH 3554": 2.56
  - name: "БСТ B25 F150W8"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 340
      "Песок средний Мк=2,0-2,5 класс 1": 860
      "Гравий М1000 фракции 5-20": 1040
      "Добавка в бетон SikaPlast PH 3554": 2.89
  - name: "БСТ B30 F150 W6"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 360
      "Песок средний Мк=2,0-2,5 класс 1": 840
      "Гравий М1000 фракции 5-20": 1040
      "Добавка в бетон SikaPlast PH 3554": 3.06
  - name: "БСТ B30 F200 W8"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 350
      "Песок средний Мк=2,0-2,5 класс 1": 860
      "Щебень М1200/М1400 фр.5-20 мм": 1030
      "Добавка в бетон SikaPlast PH 3554": 2.80
  - name: "БСТ B35 F200 W8"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 400
      "Песок средний Мк=2,0-2,5 класс 1": 810
      "Щебень М1200/М1400 фр.5-20 мм": 1030
      "Добавка в бетон SikaPlast PH 3554": 3.20
  - name: "БСТ B40 F300 W10"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 430
      "Песок средний Мк=2,0-2,5 класс 1": 780
      "Щебень М1200/М1400 фр.5-20 мм": 1030
      "Добавка в бетон SikaPlast PH 3554": 3.44
  - name: "Растворная смесь М100"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 270
      "Песок средний Мк=2,0-2,5 класс 1": 1490
      "Комплексная зимняя добавка в бетон SikaTard M Nord NF": 0.81
  - name: "Растворная смесь М150"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 330
      "Песок средний Мк=2,0-2,5 класс 1": 1470
      "Комплексная зимняя добавка в бетон SikaTard M Nord NF": 0.99
  - name: "Растворная смесь М200"
    materials:
      "Цемент ЦЕМ I 42,5Б/42,5Н": 410
      "Песок средний Мк=2,0-2,5 класс 1": 1450
      "Комплексная зимняя добавка в бетон SikaTard M Nord NF": 1.23
